// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace LINQ2DB_MVC_Core_5.DB
{
	public partial class LinqDB : DataConnection
	{
		public LinqDB()
		{
			InitDataContext();
		}

		public LinqDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public LinqDB(DataOptions<LinqDB> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}
}
